version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Singapore"
    reviewers:
      - "francisroystanley"
    target-branch: "bot-branch"
    open-pull-requests-limit: 10
